### ISSUE TITLE
E-mails not in inbox?

### ISSUE THREAD

**Issue by PeterLustig** [olia-dev/kopano-webapp-fetchmail#7] opened 2018-02-27 10:12 UTC
Hello,

I set up the fetchmail plugin and polling seems to work, but e-mails are not send to the inbox.
Am I missing something?

Thank you.

**Comment by olia-dev** [comment] 2018-02-27 17:01
Hello,

please check if the time stamp in "last polling" has updated (see screenshot: https://github.com/olia-dev/kopano-webapp-fetchmail/blob/master/screenshots/fetchmail_settings_overview_with_error.png?raw=true)

If yes, double click the entry, and copy+paste the log message here.
If no, then the daemon is probably not running, check the manual on how to configure/start the polling daemon.

Regards,
olia

**Comment by PeterLustig** [comment] 2018-02-28 08:04
It has updated, but the log message is in german.
It roughly translates as "No new mails for xx@mail.com from smtp.mail.com"
When I send a mail it reads that there was 1 new mail received.
But they don't show in the inbox.

**Comment by olia-dev** [comment] 2018-03-02 15:16
That means fetchmail is working. Fetchmail delivers your email via the local mail delivery agent (in most cases postfix).
At this point I would advise you to check the postfix logs, maybe emails get rejected or not delivered. If you post them here, I will look over them too. 
Use pastebin.com to post larger logs.

**Comment by enolacambridge** [comment] 2018-03-19 17:28
@olia-dev 
I've setup a Univention Corporate Server with Fetchmail and Kopano. Local mail delivery is working just fine and i can also receive messages from one of my other mailboxes if I input the settings in the remote mail retrieval option in Univention Management Console which is enabled when you install Fetchmail.

The issue I'm having is that when the daemon of the fetchmail plugin is running it polls the emails from the remote mailbox but they don't end up in my local mailbox.
Logic suggests that the issue is with local mail delivery but as I said before, it works just fine if the daemon is not running.

Here's the screenshot of the polling https://pasteboard.co/HcEnXBd.png 
And here the log from Postfix https://pastebin.com/4ktrHKaN

I'm using UCS 4.3-0 with Fetchmail 6.3.26 over http. Any help would be greatly appreciated.

**Comment by olia-dev** [comment] 2018-03-22 09:26
Could you post an output (obv. hide sensitive information) of the fetchmail MySQL database?

I'm specifically interested in the field "kopano_mail" from the DB - so a "select kopano_mail from kopano.kopano_fetchmail" would be enough.

**Comment by fbartels** [comment] 2018-03-22 10:14
to have a backlink, this as also discussed on the Kopano forum this morning: https://forum.kopano.io/topic/1211/emails-don-t-end-up-in-inbox-when-using-fetchmail-plugin

**Comment by olia-dev** [comment] 2018-03-25 07:24
fixed with Version 1.0.2. Thanks again to @haggybear for contributing.

**Closed as completed by olia-dev** 2018-03-25 07:24 UTC
Labels: help wanted, fixed
